[package]
name = "lwip"
version = "0.1.0"
authors = ["Conrad Kramer <conrad@kramerapps.com>"]
build = "build.rs"

[dependencies]
byteorder = "1.2"
futures = "0.1"
tokio-core = "0.1"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
